// GENERATED by tools/gen_hand_light_offsets.py -- do not edit by hand.
//
// Body-relative fist positions for the Baron family, in MAP UNITS:
//   lateral = +right of the actor's facing, up = above the actor's feet (Z()).
// Rotated by the actor's yaw at upload time by RT_UploadHandGlowLights.
//
// Geometry comes from the mod's authored brightmaps. BOSS ships none of its own,
// but BOSS and BOS2 are the same artwork palette-swapped (12/12 frames verified
// pixel-identical in silhouette), so the BOS2 masks transfer. Each sprite is still
// resolved against its OWN grAb: BOSSA5 is (29,94) where BOS2A5 is (29,93).
//
// fwd is intentionally 0: the front rotation cannot show forward extension, so a
// value here would be invented.
//
// Frames I..N (death/gib) are absent on purpose: the gore reuses the same palette
// ramp as the hand glow, so lighting them would make corpses flare.
#pragma once

struct RtHandPos
{
    float lateral;
    float up;
    float fwd;
    // Intensity multiplier for THIS HAND, not this frame. One monster can
    // carry sources of different strengths at once -- the Chaingunner has a
    // muzzle flash AND a backpack indicator, and the Mastermind's eyes sit
    // at 0.10 of its gun. A per-frame scalar could not express either.
    float lightScale;
    // 0 = inherit RT_HAND_COLOR[monster]. Set when a hand's colour differs
    // from the rest of the monster: the Chaingunner's backpack is green on a
    // monster whose light is white-blue.
    unsigned colour;
    // Eyes draw from rt_eye_light_* instead of the monster's own cvars. They
    // are a different ORDER of light -- a hint on the face, not a source that
    // lights a room -- and sharing a monster cvar makes one of the two wrong.
    bool  isEye;
};

struct RtHandFrame
{
    int        count;
    RtHandPos  hands[ 4 ];
};

enum RtHandMonster
{
    RT_HAND_HELLKNIGHT = 0,  // Hell Knight
    RT_HAND_BARON = 1,  // Baron of Hell
    RT_HAND_ARCHVILE = 2,  // Arch-Vile (Unseen Evil)
    RT_HAND_CHAINGUNNER = 3,  // Chaingunner (Unseen Evil)
    RT_HAND_MASTERMIND = 4,  // Spider Mastermind (Unseen Evil)
    RT_HAND_REVENANT = 5,  // Revenant (Unseen Evil)
    RT_HAND_IMP = 6,  // Imp
    RT_HAND_NIGHTMAREIMP = 7,  // Nightmare Imp
    RT_HAND_PINKY = 8,  // Pinky
    RT_HAND_SPECTRE = 9,  // Spectre
    RT_HAND_MANCUBUS = 10,  // Mancubus
    RT_HAND_ARACHNOTRON = 11,  // Arachnotron
    RT_HAND_CYBERDEMON = 12,  // Cyberdemon
    RT_HAND_MONSTER_COUNT = 13,
};

// Indexed by sprite frame letter: A=0 .. H=7.
constexpr int RT_HAND_FRAME_COUNT = 16;

constexpr RtHandFrame RT_HAND_FRAMES[ RT_HAND_MONSTER_COUNT ][ RT_HAND_FRAME_COUNT ] = {
    // Hell Knight (BOS2)
    {
        { 3, { { -19.9f, 50.6f, 0.0f, 1.00f, 0u, false }, { 26.4f, 46.5f, 0.0f, 1.00f, 0u, false }, { 19.6f, 52.7f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // A
        { 2, { { -16.4f, 47.0f, 0.0f, 1.00f, 0u, false }, { 23.3f, 45.3f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // B
        { 2, { { -20.7f, 45.1f, 0.0f, 1.00f, 0u, false }, { 20.5f, 44.7f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // C
        { 2, { { 15.9f, 50.6f, 0.0f, 1.00f, 0u, false }, { -20.4f, 43.4f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // D
        { 2, { { 29.7f, 81.9f, 0.0f, 1.00f, 0u, false }, { -5.7f, 63.8f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // E
        { 2, { { 32.4f, 76.0f, 0.0f, 1.00f, 0u, false }, { -23.3f, 43.1f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // F
        { 2, { { -9.9f, 49.6f, 0.0f, 1.00f, 0u, false }, { -24.2f, 44.2f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // G
        { 2, { { -19.2f, 43.9f, 0.0f, 1.00f, 0u, false }, { 25.5f, 48.2f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // H
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // I
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // J
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // K
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // L
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // M
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // N
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // O
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // P
    },
    // Baron of Hell (BOSS)
    {
        { 3, { { -19.9f, 50.6f, 0.0f, 1.00f, 0u, false }, { 26.4f, 46.5f, 0.0f, 1.00f, 0u, false }, { 19.6f, 52.7f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // A
        { 2, { { -16.4f, 47.0f, 0.0f, 1.00f, 0u, false }, { 23.3f, 45.3f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // B
        { 2, { { -20.7f, 45.1f, 0.0f, 1.00f, 0u, false }, { 20.5f, 44.7f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // C
        { 2, { { 15.9f, 50.6f, 0.0f, 1.00f, 0u, false }, { -20.4f, 43.4f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // D
        { 2, { { 29.7f, 81.9f, 0.0f, 1.00f, 0u, false }, { -5.7f, 63.8f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // E
        { 2, { { 32.4f, 76.0f, 0.0f, 1.00f, 0u, false }, { -23.3f, 43.1f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // F
        { 2, { { -9.9f, 49.6f, 0.0f, 1.00f, 0u, false }, { -24.2f, 44.2f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // G
        { 2, { { -19.2f, 43.9f, 0.0f, 1.00f, 0u, false }, { 25.5f, 48.2f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // H
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // I
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // J
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // K
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // L
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // M
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // N
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // O
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // P
    },
    // Arch-Vile (Unseen Evil) (VILE)
    {
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // A
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // B
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // C
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // D
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // E
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // F
        { 2, { { -40.4f, 124.0f, 0.0f, 1.00f, 0u, false }, { 38.2f, 121.6f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // G
        { 4, { { -49.7f, 101.2f, 0.0f, 1.00f, 0u, false }, { 31.7f, 114.9f, 0.0f, 1.00f, 0u, false }, { -40.3f, 128.4f, 0.0f, 1.00f, 0u, false }, { 41.1f, 110.8f, 0.0f, 1.00f, 0u, false } } },  // H
        { 4, { { -41.6f, 128.4f, 0.0f, 1.00f, 0u, false }, { 42.4f, 98.7f, 0.0f, 1.00f, 0u, false }, { 33.7f, 122.5f, 0.0f, 1.00f, 0u, false }, { -54.8f, 102.3f, 0.0f, 1.00f, 0u, false } } },  // I
        { 4, { { -33.9f, 87.7f, 0.0f, 1.00f, 0u, false }, { 30.4f, 117.1f, 0.0f, 1.00f, 0u, false }, { 34.1f, 86.7f, 0.0f, 1.00f, 0u, false }, { -29.8f, 110.9f, 0.0f, 1.00f, 0u, false } } },  // J
        { 4, { { -0.0f, 78.9f, 0.0f, 1.00f, 0u, false }, { 15.2f, 62.1f, 0.0f, 1.00f, 0u, false }, { -13.4f, 62.4f, 0.0f, 1.00f, 0u, false }, { 13.8f, 49.5f, 0.0f, 1.00f, 0u, false } } },  // K
        { 4, { { -12.7f, 63.4f, 0.0f, 1.00f, 0u, false }, { 5.8f, 77.4f, 0.0f, 1.00f, 0u, false }, { 12.9f, 62.9f, 0.0f, 1.00f, 0u, false }, { -0.4f, 53.5f, 0.0f, 1.00f, 0u, false } } },  // L
        { 4, { { -0.1f, 59.0f, 0.0f, 1.00f, 0u, false }, { 1.5f, 75.0f, 0.0f, 1.00f, 0u, false }, { -5.9f, 77.0f, 0.0f, 1.00f, 0u, false }, { -4.4f, 65.1f, 0.0f, 1.00f, 0u, false } } },  // M
        { 2, { { -2.8f, 70.7f, 0.0f, 1.00f, 0u, false }, { 9.2f, 61.8f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // N
        { 2, { { 1.2f, 68.1f, 0.0f, 1.00f, 0u, false }, { -17.1f, 79.2f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // O
        { 4, { { -15.7f, 51.5f, 0.0f, 1.00f, 0u, false }, { 15.8f, 53.5f, 0.0f, 1.00f, 0u, false }, { -20.9f, 52.6f, 0.0f, 1.00f, 0u, false }, { 22.1f, 80.4f, 0.0f, 1.00f, 0u, false } } },  // P
    },
    // Chaingunner (Unseen Evil) (CPOS)
    {
        { 1, { { -5.7f, 66.8f, -10.0f, 0.45f, 0x45b42cu, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // A
        { 1, { { -2.0f, 69.1f, -10.0f, 0.45f, 0x45b42cu, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // B
        { 1, { { 6.4f, 66.8f, -10.0f, 0.45f, 0x45b42cu, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // C
        { 1, { { 3.3f, 69.1f, -10.0f, 0.45f, 0x45b42cu, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // D
        { 1, { { 0.9f, 63.0f, -10.0f, 0.45f, 0x45b42cu, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // E
        { 3, { { -19.6f, 37.8f, 0.0f, 1.00f, 0u, false }, { 19.4f, 37.6f, 0.0f, 1.00f, 0u, false }, { 0.9f, 63.0f, -10.0f, 0.45f, 0x45b42cu, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // F
        { 1, { { -4.2f, 62.0f, -10.0f, 0.45f, 0x45b42cu, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // G
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // H
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // I
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // J
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // K
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // L
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // M
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // N
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // O
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // P
    },
    // Spider Mastermind (Unseen Evil) (SPID)
    {
        { 2, { { -13.4f, 98.8f, 0.0f, 0.10f, 0u, false }, { 13.2f, 98.8f, 0.0f, 0.10f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // A
        { 2, { { 12.6f, 100.9f, 0.0f, 0.10f, 0u, false }, { -14.1f, 100.8f, 0.0f, 0.10f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // B
        { 2, { { 12.1f, 103.1f, 0.0f, 0.10f, 0u, false }, { -14.7f, 102.5f, 0.0f, 0.10f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // C
        { 2, { { -13.4f, 98.8f, 0.0f, 0.10f, 0u, false }, { 13.2f, 98.8f, 0.0f, 0.10f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // D
        { 2, { { 12.6f, 100.9f, 0.0f, 0.10f, 0u, false }, { -14.1f, 100.8f, 0.0f, 0.10f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // E
        { 2, { { 12.1f, 103.1f, 0.0f, 0.10f, 0u, false }, { -14.7f, 102.5f, 0.0f, 0.10f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // F
        { 2, { { 12.5f, 88.7f, 0.0f, 0.10f, 0u, false }, { -14.8f, 88.8f, 0.0f, 0.10f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // G
        { 3, { { -0.7f, 39.1f, 0.0f, 1.00f, 0u, false }, { -0.9f, 27.2f, 0.0f, 1.00f, 0u, false }, { -1.0f, 55.3f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // H
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // I
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // J
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // K
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // L
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // M
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // N
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // O
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // P
    },
    // Revenant (Unseen Evil) (SKEL)
    {
        { 4, { { -20.0f, 113.5f, 0.0f, 1.00f, 0u, false }, { -0.5f, 107.0f, 0.0f, 1.00f, 0u, false }, { 5.5f, 107.0f, 0.0f, 1.00f, 0u, false }, { 20.0f, 115.0f, 0.0f, 1.00f, 0u, false } } },  // A
        { 3, { { -24.5f, 112.0f, 0.0f, 1.00f, 0u, false }, { 4.0f, 108.0f, 0.0f, 1.00f, 0u, false }, { -2.0f, 109.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // B
        { 2, { { -2.0f, 114.0f, 0.0f, 1.00f, 0u, false }, { 4.0f, 114.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // C
        { 3, { { 19.0f, 113.5f, 0.0f, 1.00f, 0u, false }, { -0.5f, 107.0f, 0.0f, 1.00f, 0u, false }, { -6.0f, 107.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // D
        { 2, { { 23.5f, 112.0f, 0.0f, 1.00f, 0u, false }, { 1.0f, 109.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // E
        { 1, { { 1.0f, 114.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // F
        { 3, { { 24.2f, 98.8f, 0.0f, 1.00f, 0u, false }, { -1.0f, 95.5f, 0.0f, 1.00f, 0u, false }, { 4.0f, 96.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // G
        { 1, { { 5.0f, 109.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // H
        { 3, { { -26.6f, 85.2f, 0.0f, 1.00f, 0u, false }, { 10.0f, 110.7f, 0.0f, 1.00f, 0u, false }, { -3.5f, 93.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // I
        { 4, { { -15.3f, 93.7f, 0.0f, 1.00f, 0u, false }, { 22.2f, 92.5f, 0.0f, 1.00f, 0u, false }, { 5.7f, 97.1f, 0.0f, 1.00f, 0u, false }, { -2.6f, 96.7f, 0.0f, 1.00f, 0u, false } } },  // J
        { 3, { { 0.0f, 106.5f, 0.0f, 1.00f, 0u, false }, { -5.0f, 106.0f, 0.0f, 1.00f, 0u, false }, { 19.0f, 109.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // K
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // L
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // M
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // N
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // O
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // P
    },
    // Imp (TROO)
    {
        { 2, { { 1.9f, 81.8f, 0.0f, 1.00f, 0u, true }, { -4.8f, 81.9f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // A
        { 2, { { -6.3f, 77.0f, 0.0f, 1.00f, 0u, true }, { 0.6f, 76.9f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // B
        { 2, { { -1.8f, 80.6f, 0.0f, 1.00f, 0u, true }, { 5.1f, 80.9f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // C
        { 2, { { -2.0f, 77.9f, 0.0f, 1.00f, 0u, true }, { 4.5f, 77.5f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // D
        { 1, { { -1.5f, 79.5f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // E
        { 1, { { -1.5f, 79.5f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // F
        { 2, { { 4.8f, 77.0f, 0.0f, 1.00f, 0u, true }, { -1.0f, 77.0f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // G
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // H
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // I
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // J
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // K
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // L
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // M
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // N
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // O
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // P
    },
    // Nightmare Imp (TRO2)
    {
        { 2, { { 1.9f, 81.8f, 0.0f, 1.00f, 0u, true }, { -4.8f, 81.9f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // A
        { 2, { { -6.3f, 77.0f, 0.0f, 1.00f, 0u, true }, { 0.6f, 76.9f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // B
        { 2, { { -1.8f, 80.6f, 0.0f, 1.00f, 0u, true }, { 5.1f, 80.9f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // C
        { 2, { { -2.0f, 77.9f, 0.0f, 1.00f, 0u, true }, { 4.5f, 77.5f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // D
        { 1, { { -1.5f, 79.5f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // E
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // F
        { 2, { { 4.8f, 77.0f, 0.0f, 1.00f, 0u, true }, { -1.0f, 77.0f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // G
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // H
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // I
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // J
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // K
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // L
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // M
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // N
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // O
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // P
    },
    // Pinky (SARG)
    {
        { 2, { { -2.8f, 64.9f, 0.0f, 1.00f, 0u, true }, { 7.7f, 64.2f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // A
        { 2, { { -4.0f, 59.0f, 0.0f, 1.00f, 0u, true }, { 5.3f, 58.8f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // B
        { 2, { { 3.5f, 62.0f, 0.0f, 1.00f, 0u, true }, { -6.1f, 61.3f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // C
        { 2, { { 5.4f, 59.2f, 0.0f, 1.00f, 0u, true }, { -4.8f, 59.6f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // D
        { 2, { { 3.1f, 72.7f, 0.0f, 1.00f, 0u, true }, { -7.0f, 69.3f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // E
        { 2, { { -7.4f, 69.3f, 0.0f, 1.00f, 0u, true }, { 3.8f, 72.8f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // F
        { 2, { { -7.1f, 63.2f, 0.0f, 1.00f, 0u, true }, { 3.7f, 64.0f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // G
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // H
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // I
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // J
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // K
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // L
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // M
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // N
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // O
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // P
    },
    // Spectre (SAR2)
    {
        { 2, { { -2.8f, 64.9f, 0.0f, 1.00f, 0u, true }, { 7.7f, 64.2f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // A
        { 2, { { -4.0f, 59.0f, 0.0f, 1.00f, 0u, true }, { 5.3f, 58.8f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // B
        { 2, { { 3.5f, 62.0f, 0.0f, 1.00f, 0u, true }, { -6.1f, 61.3f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // C
        { 2, { { 5.4f, 59.2f, 0.0f, 1.00f, 0u, true }, { -4.8f, 59.6f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // D
        { 2, { { 3.1f, 72.7f, 0.0f, 1.00f, 0u, true }, { -7.0f, 69.3f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // E
        { 2, { { -7.4f, 69.3f, 0.0f, 1.00f, 0u, true }, { 3.8f, 72.8f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // F
        { 2, { { -7.1f, 63.2f, 0.0f, 1.00f, 0u, true }, { 3.7f, 64.0f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // G
        { 2, { { 3.7f, 69.0f, 0.0f, 1.00f, 0u, true }, { -5.7f, 68.2f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // H
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // I
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // J
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // K
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // L
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // M
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // N
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // O
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // P
    },
    // Mancubus (FATT)
    {
        { 2, { { 8.0f, 94.3f, 0.0f, 1.00f, 0u, true }, { -0.5f, 95.5f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // A
        { 2, { { 15.0f, 94.3f, 0.0f, 1.00f, 0u, true }, { 6.3f, 95.3f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // B
        { 2, { { 0.3f, 96.3f, 0.0f, 1.00f, 0u, true }, { 8.5f, 96.0f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // C
        { 1, { { -8.7f, 94.3f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // D
        { 2, { { -4.3f, 94.3f, 0.0f, 1.00f, 0u, true }, { -13.5f, 93.5f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // E
        { 2, { { 2.5f, 95.0f, 0.0f, 1.00f, 0u, true }, { -6.5f, 95.0f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // F
        { 2, { { -4.0f, 98.2f, 0.0f, 1.00f, 0u, true }, { 4.0f, 98.2f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // G
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // H
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // I
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // J
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // K
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // L
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // M
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // N
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // O
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // P
    },
    // Arachnotron (BSPI)
    {
        { 2, { { 6.8f, 50.4f, 0.0f, 1.00f, 0u, true }, { -5.8f, 50.7f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // A
        { 2, { { 6.8f, 50.4f, 0.0f, 1.00f, 0u, true }, { -5.8f, 50.7f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // B
        { 2, { { 6.1f, 49.2f, 0.0f, 1.00f, 0u, true }, { -7.0f, 50.0f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // C
        { 2, { { 6.1f, 49.2f, 0.0f, 1.00f, 0u, true }, { -7.0f, 50.0f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // D
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // E
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // F
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // G
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // H
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // I
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // J
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // K
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // L
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // M
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // N
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // O
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // P
    },
    // Cyberdemon (CYBR)
    {
        { 2, { { 7.7f, 150.3f, 0.0f, 1.00f, 0u, true }, { -6.7f, 149.3f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // A
        { 2, { { 9.7f, 154.3f, 0.0f, 1.00f, 0u, true }, { -5.7f, 154.3f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // B
        { 2, { { 8.7f, 150.3f, 0.0f, 1.00f, 0u, true }, { -5.7f, 150.3f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // C
        { 2, { { 6.7f, 154.3f, 0.0f, 1.00f, 0u, true }, { -8.7f, 154.3f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // D
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // E
        { 2, { { 9.7f, 153.3f, 0.0f, 1.00f, 0u, true }, { -5.7f, 153.3f, 0.0f, 1.00f, 0u, true }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // F
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // G
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // H
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // I
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // J
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // K
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // L
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // M
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // N
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // O
        { 0, { { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false }, { 0.0f, 0.0f, 0.0f, 1.00f, 0u, false } } },  // P
    },
};

// Saturation-normalised average of each monster's own lit texels, so the cast light
// agrees with the sprite glow. 0xRRGGBB.
constexpr unsigned RT_HAND_COLOR[ RT_HAND_MONSTER_COUNT ] = {
    0x08ff5eu,  // Hell Knight (BOS2)
    0xe01000u,  // Baron of Hell (BOSS)
    0xff9028u,  // Arch-Vile (Unseen Evil) (VILE)
    0xcbc6ffu,  // Chaingunner (Unseen Evil) (CPOS)
    0xff140cu,  // Spider Mastermind (Unseen Evil) (SPID)
    0xff1c12u,  // Revenant (Unseen Evil) (SKEL)
    0xfe0900u,  // Imp (TROO)
    0x7763feu,  // Nightmare Imp (TRO2)
    0xff0900u,  // Pinky (SARG)
    0xff0900u,  // Spectre (SAR2)
    0xff0a00u,  // Mancubus (FATT)
    0xff0a00u,  // Arachnotron (BSPI)
    0xff0a00u,  // Cyberdemon (CYBR)
};
