// GENERATED by tools/gen_switch_lights.py — do not edit by hand.
//
// One row per LIT switch face: the bare 32x32 patch and every CMPSW* wall panel
// that stamps it. Position is the centroid of the texture's own emissive mask in
// TEXEL space from the top-left; colour is that mask's hue at full saturation, so
// the cast light and the on-screen glow are measured from the same pixels.
//
// `lit` is the mask's texel count: a pair of eyes is ~7, a panel gem ~40. The
// engine uses it to scale intensity, so one cvar covers both without a per-family
// table to keep in step.
//
// Which frame is lit is NOT the A/B letter — SWXCL and SWXCKL light on A. The rows
// come from which textures actually have a mask, so that is handled by construction.
#pragma once

struct RtSwitchLight
{
    const char* tex;   // texture name as the engine sees it, UPPERCASE
    float       tw, th; // texture size in texels
    float       cx, cy; // lit centroid, texels from the TOP-left
    int         lit;    // lit texel count
    unsigned    rgb;    // 0xRRGGBB
};

constexpr int RT_SWITCH_LIGHT_COUNT = 67;

constexpr RtSwitchLight RT_SWITCH_LIGHTS[ RT_SWITCH_LIGHT_COUNT ] = {
    { "CMPSW01B", 128.f, 256.f, 64.03f, 214.59f, 47, 0x73ff6du },
    { "CMPSW02B", 64.f, 128.f, 32.17f, 97.43f, 45, 0x72fe6cu },
    { "CMPSW03B", 64.f, 128.f, 31.98f, 93.24f, 46, 0xff1e32u },
    { "CMPSW05B", 64.f, 128.f, 32.03f, 94.59f, 47, 0x73ff6du },
    { "CMPSW06B", 64.f, 128.f, 32.03f, 94.59f, 47, 0x73ff6du },
    { "CMPSW07B", 64.f, 128.f, 31.88f, 87.04f, 26, 0x7efe7eu },
    { "CMPSW08B", 128.f, 128.f, 64.03f, 94.59f, 47, 0x73ff6du },
    { "CMPSW09B", 64.f, 128.f, 31.88f, 87.04f, 26, 0x7efe7eu },
    { "CMPSW10B", 64.f, 128.f, 31.88f, 87.04f, 26, 0x7efe7eu },
    { "CMPSW11B", 64.f, 128.f, 32.00f, 87.10f, 70, 0x77ff77u },
    { "CMPSW12B", 64.f, 128.f, 32.03f, 94.59f, 47, 0x73ff6du },
    { "CMPSW13B", 32.f, 128.f, 16.03f, 94.59f, 47, 0x73ff6du },
    { "CMPSW14B", 64.f, 128.f, 31.88f, 87.04f, 26, 0x7efe7eu },
    { "CMPSW15B", 64.f, 128.f, 31.88f, 87.04f, 26, 0x7efe7eu },
    { "CMPSW16B", 64.f, 128.f, 32.17f, 97.43f, 45, 0x72fe6cu },
    { "CMPSW17B", 64.f, 128.f, 31.98f, 93.24f, 46, 0xff1e32u },
    { "CMPSW18B", 64.f, 128.f, 32.03f, 94.59f, 47, 0x73ff6du },
    { "CMPSW19B", 64.f, 128.f, 31.98f, 93.24f, 46, 0xff1e32u },
    { "CMPSW20B", 64.f, 128.f, 32.03f, 94.59f, 47, 0x73ff6du },
    { "CMPSW21B", 64.f, 128.f, 31.88f, 87.04f, 26, 0x7efe7eu },
    { "CMPSW23A", 64.f, 128.f, 32.00f, 96.00f, 8, 0xff0000u },
    { "CMPSW24B", 64.f, 128.f, 32.06f, 97.22f, 18, 0xef0effu },
    { "CMPSW25B", 64.f, 128.f, 32.06f, 97.22f, 18, 0xef0effu },
    { "CMPSW26A", 64.f, 128.f, 32.00f, 96.00f, 8, 0xff0000u },
    { "CMPSW27B", 64.f, 128.f, 31.93f, 95.79f, 7, 0xfe2f03u },
    { "CMPSW28A", 64.f, 256.f, 32.00f, 224.00f, 8, 0xff0000u },
    { "CMPSW29A", 64.f, 128.f, 32.00f, 32.00f, 8, 0xff0000u },
    { "CMPSW30B", 64.f, 128.f, 31.93f, 95.79f, 7, 0xfe2f03u },
    { "CMPSW31B", 64.f, 128.f, 32.06f, 97.22f, 18, 0xef0effu },
    { "CMPSW32A", 64.f, 128.f, 32.00f, 95.75f, 8, 0xff1703u },
    { "CMPSW33A", 64.f, 128.f, 32.00f, 95.75f, 8, 0xff1703u },
    { "CMPSW34B", 64.f, 128.f, 31.93f, 32.79f, 7, 0xfe2f03u },
    { "CMPSW35B", 64.f, 128.f, 31.93f, 95.79f, 7, 0xfe2f03u },
    { "CMPSW36B", 64.f, 128.f, 31.93f, 95.79f, 7, 0xfe2f03u },
    { "CMPSW37B", 64.f, 128.f, 31.93f, 95.79f, 7, 0xfe2f03u },
    { "CMPSW38B", 64.f, 128.f, 31.93f, 95.79f, 7, 0xfe2f03u },
    { "CMPSW39B", 64.f, 128.f, 31.93f, 95.79f, 7, 0xfe2f03u },
    { "CMPSW41B", 64.f, 128.f, 31.93f, 95.79f, 7, 0xfe2f03u },
    { "CMPSW42B", 64.f, 128.f, 31.93f, 95.79f, 7, 0xfe2f03u },
    { "CMPSW43B", 64.f, 128.f, 31.93f, 95.79f, 7, 0xfe2f03u },
    { "CMPSW44B", 64.f, 128.f, 31.93f, 95.79f, 7, 0xfe2f03u },
    { "CMPSW45A", 64.f, 128.f, 32.00f, 96.00f, 8, 0xff0000u },
    { "CMPSW46B", 64.f, 128.f, 31.93f, 95.79f, 7, 0xfe2f03u },
    { "CMPSW47A", 64.f, 128.f, 32.00f, 96.00f, 8, 0xff0000u },
    { "CMPSW48B", 64.f, 256.f, 31.93f, 215.79f, 7, 0xfe2f03u },
    { "CMPSW49B", 64.f, 256.f, 31.93f, 223.79f, 7, 0xfe2f03u },
    { "CMPSW50B", 64.f, 128.f, 32.06f, 89.22f, 18, 0xef0effu },
    { "CMPSW52B", 64.f, 128.f, 31.93f, 95.79f, 7, 0xfe2f03u },
    { "CMPSW53B", 64.f, 128.f, 31.93f, 79.79f, 7, 0xfe2f03u },
    { "CMPSW54B", 64.f, 128.f, 32.00f, 87.10f, 70, 0x77ff77u },
    { "CMPSW55B", 64.f, 128.f, 31.98f, 93.24f, 46, 0xff1e32u },
    { "CMPSW56B", 64.f, 128.f, 31.48f, 91.83f, 84, 0x69ff69u },
    { "CMPSW57B", 64.f, 128.f, 32.17f, 97.43f, 45, 0x72fe6cu },
    { "CMPSW58B", 64.f, 128.f, 31.48f, 91.83f, 84, 0x69ff69u },
    { "CMPSW59B", 64.f, 192.f, 32.03f, 164.59f, 47, 0x73ff6du },
    { "CMPSW62B", 32.f, 128.f, 15.93f, 79.79f, 7, 0xfe2f03u },
    { "SWXCB", 32.f, 32.f, 15.93f, 15.79f, 7, 0xfe2f03u },
    { "SWXCKB", 32.f, 32.f, 16.06f, 17.22f, 18, 0xef0effu },
    { "SWXCKLA", 32.f, 32.f, 16.00f, 16.00f, 8, 0xff0000u },
    { "SWXCLA", 32.f, 32.f, 16.00f, 15.75f, 8, 0xff1703u },
    { "SWXS4B", 24.f, 24.f, 12.00f, 12.50f, 132, 0x0bffb2u },
    { "SWXSAB", 32.f, 32.f, 15.88f, 7.04f, 26, 0x7efe7eu },
    { "SWXSCB", 32.f, 32.f, 16.17f, 17.43f, 45, 0x72fe6cu },
    { "SWXSDB", 32.f, 32.f, 16.03f, 14.59f, 47, 0x73ff6du },
    { "SWXSEB", 32.f, 32.f, 15.48f, 11.83f, 84, 0x69ff69u },
    { "SWXSFB", 32.f, 32.f, 16.00f, 7.10f, 70, 0x77ff77u },
    { "SWXSGB", 32.f, 32.f, 15.98f, 13.24f, 46, 0xff1e32u },
};
