// Doom64-RT: WHAT A WALL IS MADE OF.
//
// Split out of rt_sparks.cpp, which had reached 4126 lines. This half answers
// exactly one question -- "what is this surface" -- and everything that depends
// on the answer (which particles an impact throws, what colour they are, how
// they fall) lives elsewhere. See rt_sparks_internal.h for the split.
//
// THE CLASSIFICATION IS NOT OURS. rt/data/spark_surfaces.txt is generated by
// tools/build_spark_surfaces.py out of the `surface` field in
// tools/_material_labels/*.json -- the same hand-labelling pass that authors
// metallicDefault and roughnessDefault, and which was already recording
// "metal" / "concrete" / "other" while nothing consumed it. That pipeline
// belongs to the PBR material work; this file is a read-only consumer of it and
// must stay one.
//
// The rule the whole thing rests on is OPT-IN: a texture has to be positively
// labelled to behave differently, and anything unlabelled answers Other and
// keeps the shipped spark. The first version had it the other way round --
// metal sparks, everything else is debris -- which was wrong for the state the
// data is actually in: the labelling covers a fraction of the game's 2331
// textures, so "everything not metal" meant almost every wall in it.

#include "rt_sparks_internal.h"

#include "bitmap.h"
#include "palutil.h"

#include <fstream>
#include <string>
#include <unordered_map>

using namespace rtx;

namespace rtsp
{

// DEBRIS gets its own ramp, and it is deliberately NOT a dimmed spark ramp: a
// chip of wall is cool, dusty and slightly warm-grey, and it does not cool as it
// falls because it was never hot. It darkens slightly as it tumbles out of the
// light, which is the only change along its life.
//
// The real colour of a chip is the surface it came off, and this is the
// placeholder for that: FTraceResults carries HitTexture, so the hit texture's
// own average albedo is reachable and is the obvious upgrade once the metal
// classification exists to make debris worth looking at. Until then a neutral
// ramp is honest, and a WRONG per-surface colour would be worse than a neutral
// one.
// THESE ARE ALBEDOS, NOT PIXEL COLOURS, and that is why the first set read far
// too bright. Debris is ray-traced geometry now, so the ramp is what the path
// tracer MULTIPLIES the room's light by -- a value of 0.60 (0x9A) is a white
// laboratory tile, not a chip of wall. Real rock and concrete sit around
// 0.20-0.35, and the top of each ramp is chosen there. The old numbers were
// picked while debris was still a rasterized overlay, where the ramp WAS the
// final colour and 0.60 was reasonable; the move to traced geometry silently
// changed what they mean. Reported from play as "too bright colors".
constexpr uint32_t RT_DEBRIS_RAMP[] = {
    0x484440, 0x3D3A36, 0x33302D, 0x282623, 0x1E1C1A, 0x151412, 0x0E0D0C,
};
constexpr int RT_DEBRIS_RAMP_N = int( std::size( RT_DEBRIS_RAMP ) );

// CONCRETE gets its own, paler and dustier. Stone chips off light and throws
// pale dust; the generic "other" ramp above is darker because it covers panels,
// crates and machinery rather than masonry. Both are neutral placeholders for
// the hit texture's real albedo -- see the note above -- but a two-way split
// costs nothing and is already better than one grey for everything, now that the
// labeller distinguishes them.
constexpr uint32_t RT_CONCRETE_RAMP[] = {
    0x5A554D, 0x4E4941, 0x423E37, 0x36322D, 0x2A2723, 0x1E1C19, 0x14120F,
};
constexpr int RT_CONCRETE_RAMP_N = int( std::size( RT_CONCRETE_RAMP ) );

// Per-class fallback ramps. These are what a chip looks like BEFORE the hit
// texture's own colour is blended over them (rt_spark_debris_tint), so they only
// fully show on a texture whose average could not be read. All are albedos in
// the 0.2-0.35 band for the reason above.
constexpr uint32_t RT_WOOD_RAMP[] = {
    0x6B5334, 0x5C4830, 0x4D3D2A, 0x3F3224, 0x31281D, 0x241D15, 0x17130E,
};
constexpr int RT_WOOD_RAMP_N = int( std::size( RT_WOOD_RAMP ) );

constexpr uint32_t RT_DIRT_RAMP[] = {
    0x4A3B2A, 0x403325, 0x362B20, 0x2B231A, 0x211B14, 0x17130E, 0x0F0C09,
};
constexpr int RT_DIRT_RAMP_N = int( std::size( RT_DIRT_RAMP ) );

// Blood. Darker and less saturated than the sprite art, because this is an
// ALBEDO the room lights rather than a painted pixel -- a 0.8-red droplet under
// a bright lamp reads as neon.
constexpr uint32_t RT_FLESH_RAMP[] = {
    0x6E1512, 0x5E120F, 0x4E0F0D, 0x3F0C0A, 0x300908, 0x220706, 0x160404,
};
constexpr int RT_FLESH_RAMP_N = int( std::size( RT_FLESH_RAMP ) );

// Fluid barely uses its ramp: its whole point is to be the colour of the liquid
// it came out of, so its profile drives the tint to 1 and this is only the
// fallback for a texture that could not be sampled.
constexpr uint32_t RT_FLUID_RAMP[] = {
    0x40564A, 0x384C42, 0x304139, 0x28362F, 0x1F2A25, 0x161E1A, 0x0E1310,
};
constexpr int RT_FLUID_RAMP_N = int( std::size( RT_FLUID_RAMP ) );

// THE COLOUR OF THE WALL YOU JUST SHOT
//
// A chip should be the colour of what it was chipped off, and the whole reason
// that is now possible is the HitTexture fix: the hook derives the wall texture
// itself, so a valid FTextureID reaches this file where before every impact
// arrived with an empty one.
//
// Averaged with gzdoom's own averageColor() over the texture's BGRA bitmap --
// the same call FGameTexture::GetGlowColor uses. NOTE the third argument:
// GetGlowColor passes 153, which NORMALIZES the result so the peak channel hits
// that value, brightening a dull texture into a saturated glow hue. That is
// exactly wrong here. An albedo wants the TRUE mean, so this passes 0.
//
// CACHED PER TEXTURE, and it has to be: GetBgraBitmap decodes the whole image,
// which is far too expensive to do per impact, let alone per chip. Computed once
// on first hit and kept -- a level has a few dozen distinct wall textures.
std::unordered_map< int, uint32_t > s_texAvgCache;

uint32_t AverageTextureColor( FTextureID tex )
{
    if( !tex.isValid() )
    {
        return 0x808080;
    }

    const int key = tex.GetIndex();
    if( auto it = s_texAvgCache.find( key ); it != s_texAvgCache.end() )
    {
        return it->second;
    }

    uint32_t out = 0x808080;

    if( FGameTexture* gt = TexMan.GetGameTexture( tex ) )
    {
        if( FTexture* base = gt->GetTexture() )
        {
            FBitmap bmp = base->GetBgraBitmap( nullptr );
            const int n = bmp.GetWidth() * bmp.GetHeight();
            if( n > 0 )
            {
                // maxout 0 -> the honest mean. See the note above.
                const PalEntry c =
                    averageColor( reinterpret_cast< const uint32_t* >( bmp.GetPixels() ), n, 0 );
                out = ( uint32_t( c.r ) << 16 ) | ( uint32_t( c.g ) << 8 ) | uint32_t( c.b );
            }
        }
    }

    s_texAvgCache[ key ] = out;
    return out;
}



SurfKind ParseSurfKind( const FString& s )
{
    if( s.IsEmpty() || s.CompareNoCase( "metal" ) == 0 )
    {
        // Empty means a bare NAME with no class column: that was the first
        // version of this file, where listing a texture at all meant metal.
        return SurfKind::Metal;
    }
    if( s.CompareNoCase( "concrete" ) == 0 ) return SurfKind::Concrete;
    if( s.CompareNoCase( "wood" ) == 0 )     return SurfKind::Wood;
    if( s.CompareNoCase( "dirt" ) == 0 )     return SurfKind::Dirt;
    if( s.CompareNoCase( "flesh" ) == 0 )    return SurfKind::Flesh;
    if( s.CompareNoCase( "fluid" ) == 0 )    return SurfKind::Fluid;
    return SurfKind::Other;
}

const char* SurfKindName( SurfKind k )
{
    switch( k )
    {
        case SurfKind::Metal: return "metal";
        case SurfKind::Concrete: return "concrete";
        case SurfKind::Wood: return "wood";
        case SurfKind::Dirt: return "dirt";
        case SurfKind::Flesh: return "flesh";
        case SurfKind::Fluid: return "fluid";
        case SurfKind::Barrel: return "barrel";
        default: return "other";
    }
}

// Which classes throw debris at all. Metal and Other spark -- see the opt-in
// rule: a texture must be positively labelled something else to change.
bool SurfThrowsDebris( SurfKind k )
{
    return k != SurfKind::Metal && k != SurfKind::Other;
}

// Indexed by SurfKind. Metal and Other are present but never used (they spark),
// and are filled with the concrete row so an indexing mistake is dull rather
// than undefined.
constexpr DebrisProfile RT_DEBRIS_PROFILES[ int( SurfKind::COUNT ) ] = {
    // Metal -- unused, sparks.
    { RT_CONCRETE_RAMP, RT_CONCRETE_RAMP_N, nullptr,
      1.f, 1.f, 1.f, 1.f, 1.f, 1.f, 1.f, 0.55f, 1.65f, 1.f, 1.f, 1.f },

    // CONCRETE: the reference row. Blocky chips, heavy, barely bouncy.
    { RT_CONCRETE_RAMP, RT_CONCRETE_RAMP_N, nullptr,
      1.f, 1.f, 1.f, 1.f, 1.f, 1.f, 1.f, 0.55f, 1.65f, 1.f, 1.f, 1.f },

    // WOOD: SPLINTERS. The aspect range is the whole read -- long and thin, and
    // never square. Lighter than stone so it falls slower and further, tumbles
    // much faster (a flat splinter catches air), and bounces a little more.
    { RT_WOOD_RAMP, RT_WOOD_RAMP_N, nullptr,
      1.1f, 1.15f, 1.f, 1.15f, 0.62f, 1.5f, 0.8f, 0.12f, 0.35f, 2.2f, 1.f, 1.1f },

    // DIRT: crumbs. Many, small, and they DO NOT BOUNCE -- dirt hits and stops,
    // which is what separates it from concrete at a glance. High friction so the
    // few that do skid stop immediately.
    //
    // LIFE 1.0, i.e. the full rt_spark_debris_life like concrete and wood. It was
    // 0.55 on the reasoning that loose earth does not lie around as debris; in
    // play that just made dirt vanish while the chips beside it stayed, which
    // reads as the effect failing rather than as a material difference. The
    // three solid classes now share one lifetime and differ only in how they
    // move, which is the axis that actually carries them.
    { RT_DIRT_RAMP, RT_DIRT_RAMP_N, nullptr,
      1.8f, 0.6f, 1.f, 0.85f, 1.15f, 0.12f, 2.2f, 0.7f, 1.4f, 1.f, 1.f, 0.9f },

    // FLESH: blood droplets. Round-ish, wet, and they SPLAT rather than bounce.
    // Slower and fatter than a chip, and short-lived: a droplet in flight is a
    // moment, and the lasting mark is the blood decal system's job, not this.
    { RT_FLESH_RAMP, RT_FLESH_RAMP_N, nullptr,
      1.6f, 0.85f, 0.35f, 0.9f, 1.25f, 0.05f, 2.5f, 0.8f, 1.25f, 0.5f, 0.75f, 1.15f },

    // FLUID: a splash. The most droplets of anything, small and fast, thrown
    // wide, gone quickly. tint 1.18 pushes rt_spark_debris_tint past 1 so it
    // CLAMPS at full texture colour -- "coloured the same as the texture" is the
    // requirement, so the neutral ramp must not show through at all. The albedo
    // is raised too: a liquid reads brighter than rubble.
    { RT_FLUID_RAMP, RT_FLUID_RAMP_N, nullptr,
      2.4f, 0.5f, 0.3f, 1.35f, 1.f, 0.08f, 2.2f, 0.75f, 1.3f, 1.f, 1.18f, 1.5f },

    // Other -- unused, sparks.
    { RT_CONCRETE_RAMP, RT_CONCRETE_RAMP_N, nullptr,
      1.f, 1.f, 1.f, 1.f, 1.f, 1.f, 1.f, 0.55f, 1.65f, 1.f, 1.f, 1.f },

    // BARREL PLATE. Not a surface anyone can be standing on -- see the note on
    // SurfKind::Barrel -- so half this row is dead and it is worth saying which
    // half rather than leaving the reader to check.
    //
    // LIVE:  the ramp (the age curve for a shard's own sprite colour), and
    //        gravity / bounce / friction, which the sim reads for every chunk.
    //        Aspect too: SpawnBarrelShards draws from this range, so the plate
    //        proportions live here beside every other material's.
    // DEAD:  count / size / life / speed, because a barrel does not spawn
    //        through RT_SpawnImpactSparks -- it has its own rt_barrel_* knobs.
    //        tint / albedo, because the shard colour path bypasses the whole
    //        luminance-pinning pipeline these two drive.
    //
    // The numbers that are live say "heavy sheet steel": a shade heavier than
    // concrete, almost no bounce, high friction so a landed piece stops rather
    // than skating, and a SLOW tumble. Slow is deliberate -- a fast-spinning
    // quarter-metre plate strobes as it passes edge-on and reads as a rendering
    // fault, which is the same trap the debris tumble is capped for.
    { RT_BARREL_RAMP, RT_BARREL_RAMP_N, nullptr,
      1.f, 1.f, 1.f, 1.f, 1.05f, 0.30f, 0.85f, 0.45f, 0.95f, 0.55f, 1.f, 1.f },
};

const DebrisProfile& ProfileFor( SurfKind k )
{
    const int i = int( k );
    return RT_DEBRIS_PROFILES[ ( i >= 0 && i < int( SurfKind::COUNT ) ) ? i : int( SurfKind::Other ) ];
}

// Which surfaces are METAL
//
// DOOM 64 TEXTURE NAMES CARRY NO MEANING -- C1, C102B, C307B1, SPACEAO1 -- so
// there is no prefix rule that separates metal from stone and this cannot be a
// pattern the way l_waterflag is. It has to be an explicit list, and an explicit
// list of a thousand entries has to be editable without a rebuild, or nobody will
// ever finish it. Hence a data file, reloadable in-game with `spark_surfaces`.
//
// The file lives in Retribution-RT-Materials/rt/data/ (tracked, and staged into
// the build tree by build-gzdoom-rt.cmd) rather than in the gitignored build rt/,
// which would be wiped by the next restage.
// ---------------------------------------------------------------------------

struct SurfEntry
{
    FString  name;
    SurfKind kind;
};

std::vector< SurfEntry > s_surfExact;
std::vector< SurfEntry > s_surfPrefix;
bool                     s_surfacesLoaded = false;
// What the last load attempt tried and whether it found anything. Reported by
// the `spark_surfaces` CCMD -- a table that silently fails to load is
// indistinguishable in play from a feature that does nothing.
FString                  s_surfacesPath;
bool                     s_surfacesFound = false;

void LoadSparkSurfaces()
{
    s_surfacesLoaded = true;
    s_surfExact.clear();
    s_surfPrefix.clear();

    // A PLAIN FILE, NOT A LUMP, and getting this wrong is why the table silently
    // did nothing on first ship.
    //
    // rt/data/ is RTGL1's own directory on disk, next to gzdoom.exe. It is NOT in
    // gzdoom's lump filesystem: that holds the IWAD, the -file PWADs and rt/wad,
    // and nothing else. fileSystem.CheckNumForFullName( "rt/data/..." ) therefore
    // always answers -1, however present the file is. Every other RT reference to
    // this tree reads it the same way this now does -- see the
    // std::filesystem::exists( "rt/bin_remix/..." ) checks in remix_launcher.cpp.
    //
    // The original version used the lump path AND treated "not found" as a silent
    // normal state, so the failure produced no output at all and read from play as
    // "the classification does nothing". Hence s_surfacesPath / s_surfacesFound
    // below: the `spark_surfaces` CCMD reports what was tried and what happened,
    // and never claims success it did not have.
    s_surfacesPath  = "rt/data/spark_surfaces.txt";
    s_surfacesFound = false;

    std::ifstream f( s_surfacesPath.GetChars(), std::ios::binary );
    if( !f.is_open() )
    {
        // Console + logfile always; the notify overlay only under rt_verbose.
        // NOT silent, whatever the cvars say: this is the state where the whole
        // classification does nothing, and it previously looked exactly like a
        // feature that had been implemented and did not work.
        Printf( RT_DiagPrintLevel(),
                "rt_spark surfaces: '%s' NOT FOUND -- every surface will classify as "
                "'other'. Run: python tools/build_spark_surfaces.py\n",
                s_surfacesPath.GetChars() );
        return;
    }

    std::string raw( ( std::istreambuf_iterator< char >( f ) ),
                     std::istreambuf_iterator< char >() );
    s_surfacesFound = true;

    FString text{ raw.c_str(), raw.size() };

    FString cur;
    auto    l_flush = [ & ]() {
        cur.StripLeftRight();
        if( cur.IsEmpty() || cur[ 0 ] == '#' )
        {
            cur = "";
            return;
        }
        // `NAME class`, with the class optional. Split on the first run of
        // whitespace; a line with no class is a bare NAME, which the first
        // version of this file used to mean metal, so ParseSurfKind maps an
        // empty class to Metal and old files keep working.
        FString nameTok = cur;
        FString kindTok;
        for( size_t k = 0; k < cur.Len(); k++ )
        {
            const char c = cur[ int( k ) ];
            if( c == ' ' || c == '\t' )
            {
                nameTok = cur.Left( k );
                kindTok = cur.Mid( k );
                kindTok.StripLeftRight();
                break;
            }
        }

        nameTok.ToUpper();
        const SurfKind kind = ParseSurfKind( kindTok );

        if( nameTok.Len() > 1 && nameTok[ nameTok.Len() - 1 ] == '*' )
        {
            nameTok.Truncate( nameTok.Len() - 1 );
            s_surfPrefix.push_back( SurfEntry{ nameTok, kind } );
        }
        else
        {
            s_surfExact.push_back( SurfEntry{ nameTok, kind } );
        }
        cur = "";
    };
    // filled in after the parse loop below

    for( size_t i = 0; i < text.Len(); i++ )
    {
        const char c = text[ int( i ) ];
        if( c == '\n' || c == '\r' )
        {
            l_flush();
        }
        else
        {
            cur += c;
        }
    }
    l_flush();

    // SIZED BY THE ENUM, not by the three classes this line happens to print.
    // It was int n[3] and indexed by int(e.kind), which for anything labelled
    // wood, dirt, flesh, fluid or other -- Other is index 6 -- wrote past the
    // end of a stack array, and read past it again to print the Other count.
    int n[ int( SurfKind::COUNT ) ]{};
    for( const SurfEntry& e : s_surfExact )
    {
        n[ int( e.kind ) ]++;
    }
    for( const SurfEntry& e : s_surfPrefix )
    {
        n[ int( e.kind ) ]++;
    }

    // One line per load, console + logfile. It answers the two questions that
    // matter -- did the table load at all, and how far has the labelling got --
    // without needing the CCMD or a debug cvar, which is the point: the previous
    // version said nothing on either success or failure.
    Printf( RT_DiagPrintLevel(),
            "rt_spark surfaces: %d entries from %s  (metal %d -> sparks, "
            "concrete %d + other %d -> debris)\n",
            int( s_surfExact.size() + s_surfPrefix.size() ),
            s_surfacesPath.GetChars(),
            n[ int( SurfKind::Metal ) ],
            n[ int( SurfKind::Concrete ) ],
            n[ int( SurfKind::Other ) ] );
}

// The surface class of a texture. Unlisted is Other, i.e. debris -- so a texture
// the labeller has not reached yet degrades to the dull effect rather than to a
// wrong hot one. `outListed` distinguishes "labelled as other" from "not
// labelled", which is the difference the surface probe has to show.
SurfKind SurfaceKindOf( FTextureID tex, FString* outName, bool* outListed )
{
    if( !s_surfacesLoaded )
    {
        LoadSparkSurfaces();
    }

    if( outListed )
    {
        *outListed = false;
    }

    FString name;
    if( tex.isValid() )
    {
        if( FGameTexture* gt = TexMan.GetGameTexture( tex ) )
        {
            name = gt->GetName();
        }
    }
    if( outName )
    {
        *outName = name;
    }
    if( name.IsEmpty() )
    {
        return SurfKind::Other;
    }

    FString up = name;
    up.ToUpper();

    // Exact wins over prefix, so a single texture can be excepted out of a
    // family rule without reordering the file.
    for( const SurfEntry& e : s_surfExact )
    {
        if( up.Compare( e.name ) == 0 )
        {
            if( outListed )
            {
                *outListed = true;
            }
            return e.kind;
        }
    }
    for( const SurfEntry& p : s_surfPrefix )
    {
        if( up.Len() >= p.name.Len() && up.Left( p.name.Len() ).Compare( p.name ) == 0 )
        {
            if( outListed )
            {
                *outListed = true;
            }
            return p.kind;
        }
    }
    return SurfKind::Other;
}

} // namespace rtsp

// The CCMD sits OUTSIDE the namespace: the macro registers a console command
// through a file-static object, and keeping it at the same scope as every other
// CCMD in the renderer is one less thing to be surprised by.
using namespace rtsp;

// Reload the metal list without restarting, because classifying 2331 textures is
// an edit-check-edit loop and a rebuild or even a level reload per entry would
// make it unbearable. Pair it with rt_spark_surface_debug 1.
CCMD( spark_surfaces )
{
    LoadSparkSurfaces();

    // SIZED BY THE ENUM, not by the three classes this line happens to print.
    // It was int n[3] and indexed by int(e.kind), which for anything labelled
    // wood, dirt, flesh, fluid or other -- Other is index 6 -- wrote past the
    // end of a stack array, and read past it again to print the Other count.
    int n[ int( SurfKind::COUNT ) ]{};
    for( const SurfEntry& e : s_surfExact )
    {
        n[ int( e.kind ) ]++;
    }
    for( const SurfEntry& e : s_surfPrefix )
    {
        n[ int( e.kind ) ]++;
    }

    if( !s_surfacesFound )
    {
        Printf( TEXTCOLOR_ORANGE
                "rt_spark surfaces: FILE NOT FOUND -- '%s'\n" TEXTCOLOR_NORMAL
                "  Every surface therefore classifies as 'other', i.e. debris when\n"
                "  rt_spark_debris is on and sparks when it is off. Run:\n"
                "    python tools/build_spark_surfaces.py\n"
                "  It writes the engine build tree AND Retribution-RT-Materials.\n",
                s_surfacesPath.GetChars() );
        return;
    }

    Printf( "rt_spark surfaces: %d entries (%d exact, %d prefix) from %s\n",
            int( s_surfExact.size() + s_surfPrefix.size() ),
            int( s_surfExact.size() ),
            int( s_surfPrefix.size() ),
            s_surfacesPath.GetChars() );
    Printf( "  metal %d (sparks)   concrete %d (debris)   other %d (debris)\n",
            n[ int( SurfKind::Metal ) ],
            n[ int( SurfKind::Concrete ) ],
            n[ int( SurfKind::Other ) ] );
    Printf( "  regenerate with: python tools/build_spark_surfaces.py  "
            "(reads the PBR labeller's `surface` field)\n" );
    SparkReportUnlisted();
    Printf( "  rt_spark_debris is %s. Set rt_spark_surface_debug 1 and shoot a "
            "wall to see what each surface is called.\n",
            cvar::rt_spark_debris ? "ON (non-metal throws debris)"
                                  : "off (everything sparks)" );
}

