// GENERATED by tools/gen_ue_fixture_lights.py -- do not edit by hand.
//
// One row per LIT wall face in Doom 64: Unseen Evil -- a door indicator on a
// frame it is actually lit on, a switch lamp in its ON texture, a light strip.
// The layout matches RtSwitchLight so RT_UploadSwitchLights can peg both the
// same way: position is the centroid of the lit mask in TEXEL space from the
// top-left, colour is that mask's hue at full saturation, `lit` is its texel
// count. `scale` is the one thing RtSwitchLight has no field for: a door's mid
// frame is the same lamp at part brightness, and without it a three-step pulse
// collapses into on/off.
//
// A STRIP IS LIT ALONG ITS LONG AXIS, and x0..y1 is how the engine knows
// which axis that is. d64_lite_thin is a 16x128 VERTICAL tube: a chain run
// along the wall put its lights side by side on a 16-unit line -- and, with
// the first light half a segment in, put NONE on a line shorter than that,
// which is every one of MAP01's. Lit up the wall instead, it is a column of
// three. d64_metal7's 64x7 bar is the other case and is lit along the wall.
//
// `band` SPLITS THE TWO SHAPES OF FIXTURE, and it is the family, not a
// measurement: a door indicator and a switch lamp are ONE object on one
// sidedef, while a light strip is wall art that TILES along the whole line.
// A strip lit as a single sphere reads as somebody dropping a dynamic point
// light on the wall -- which is exactly what it looked like -- so strips are
// walked as a chain of overlapping spheres instead, the way
// RT_UploadWallStripLights already does it. RTGL1 leaves no better option:
// an emissive surface casts no light at all, and RgLightPolygonalEXT is
// compiled out behind #if TRIANGLE_LIGHTS and hard-errors on upload.
//
// WHICH FRAME IS LIT IS NEVER ASSUMED. A row exists only where the art carries
// a lit mask, so a frame with no row emits nothing -- that IS the blink, and it
// is also why a switch lights only once thrown. See the generator's docstring
// for the two families this catches out.
#pragma once

struct RtUeFixtureLight
{
    const char* tex;    // texture name as the engine sees it, UPPERCASE
    float       tw, th; // texture size in texels
    float       cx, cy; // lit centroid, texels from the TOP-left
    int         lit;    // lit texel count
    unsigned    rgb;    // 0xRRGGBB
    float       scale;  // this frame's brightness against the family's peak
    bool        band;   // a tiling wall strip, lit as a CHAIN, not a single sphere
    int         x0, x1; // lit extent in texels, inclusive -- a strip is lit along
    int         y0, y1; //   its LONG axis, and this is what says which axis that is
};

// TWO KEYS PER FIXTURE, AND THE SECOND ONE IS NOT BELT-AND-BRACES -- it is the
// only key most of these can ever be found by.
//
// GZDoom fills FGameTexture::Name only for a pk3 texture whose basename fits
// the classic 8 characters. Unseen Evil's art mostly does not: C201 and SPACEAU
// out of textures/d64/ arrive named, while d64_metal7, d64_talldoor_2 and
// d64_greydoor_0 arrive with an EMPTY name and are reachable only through the
// file they came from. Its TEXTURES composites are a third case: their name is
// the declared path ("textures/comp/d64_exitdoor_2"), extension and all absent.
//
// Keyed on the name alone, this table matched exactly the composites -- every
// switch, and the exit door -- and silently missed every plain PNG, which is
// most of the doors and all fourteen light strips. It looked like the feature
// half-working rather than like a lookup failure. RT_UeFixtureLightFor falls
// back to fileSystem.GetFileFullName(), which is what the path rows below match.
constexpr int RT_UE_FIXTURE_LIGHT_COUNT = 166;

constexpr RtUeFixtureLight RT_UE_FIXTURE_LIGHTS[ RT_UE_FIXTURE_LIGHT_COUNT ] = {
    // ---- door
    { "D64_BEIGEDOOR_1", 64.f, 72.f, 16.50f, 66.00f, 12, 0x40ff2du, 0.754f, false, 12, 20, 64, 67 },
    { "TEXTURES/PEPY/DOORS/D64_BEIGEDOOR_1.PNG", 64.f, 72.f, 16.50f, 66.00f, 12, 0x40ff2du, 0.754f, false, 12, 20, 64, 67 },
    { "D64_BEIGEDOOR_1", 64.f, 72.f, 47.50f, 66.00f, 12, 0x40ff2du, 0.754f, false, 43, 51, 64, 67 },
    { "TEXTURES/PEPY/DOORS/D64_BEIGEDOOR_1.PNG", 64.f, 72.f, 47.50f, 66.00f, 12, 0x40ff2du, 0.754f, false, 43, 51, 64, 67 },
    { "D64_BEIGEDOOR_2", 64.f, 72.f, 16.50f, 66.00f, 12, 0x24ff21u, 1.000f, false, 12, 20, 64, 67 },
    { "TEXTURES/PEPY/DOORS/D64_BEIGEDOOR_2.PNG", 64.f, 72.f, 16.50f, 66.00f, 12, 0x24ff21u, 1.000f, false, 12, 20, 64, 67 },
    { "D64_BEIGEDOOR_2", 64.f, 72.f, 47.50f, 66.00f, 12, 0x24ff21u, 1.000f, false, 43, 51, 64, 67 },
    { "TEXTURES/PEPY/DOORS/D64_BEIGEDOOR_2.PNG", 64.f, 72.f, 47.50f, 66.00f, 12, 0x24ff21u, 1.000f, false, 43, 51, 64, 67 },
    { "D64_BIGDOOR_0", 128.f, 128.f, 103.99f, 108.44f, 63, 0x2fff29u, 1.000f, false, 99, 109, 99, 112 },
    { "TEXTURES/PEPY/D64_BIGDOOR_0.PNG", 128.f, 128.f, 103.99f, 108.44f, 63, 0x2fff29u, 1.000f, false, 99, 109, 99, 112 },
    { "D64_BIGDOOR_0", 128.f, 128.f, 23.00f, 108.58f, 62, 0x2eff27u, 1.000f, false, 18, 28, 102, 112 },
    { "TEXTURES/PEPY/D64_BIGDOOR_0.PNG", 128.f, 128.f, 23.00f, 108.58f, 62, 0x2eff27u, 1.000f, false, 18, 28, 102, 112 },
    { "D64_BIGDOOR_2", 128.f, 128.f, 22.71f, 108.78f, 29, 0x42ff2fu, 0.411f, false, 18, 26, 104, 111 },
    { "TEXTURES/PEPY/D64_BIGDOOR_2.PNG", 128.f, 128.f, 22.71f, 108.78f, 29, 0x42ff2fu, 0.411f, false, 18, 26, 104, 111 },
    { "D64_BIGDOOR_2", 128.f, 128.f, 103.71f, 108.78f, 29, 0x42ff2fu, 0.411f, false, 99, 107, 104, 111 },
    { "TEXTURES/PEPY/D64_BIGDOOR_2.PNG", 128.f, 128.f, 103.71f, 108.78f, 29, 0x42ff2fu, 0.411f, false, 99, 107, 104, 111 },
    { "D64_EXITDOOR_1", 128.f, 72.f, 31.50f, 36.72f, 88, 0x16ff1fu, 0.655f, false, 26, 36, 32, 41 },
    { "TEXTURES/COMP/D64_EXITDOOR_1", 128.f, 72.f, 31.50f, 36.72f, 88, 0x16ff1fu, 0.655f, false, 26, 36, 32, 41 },
    { "D64_EXITDOOR_1", 128.f, 72.f, 48.87f, 64.66f, 19, 0x1eff62u, 0.655f, false, 40, 60, 63, 66 },
    { "TEXTURES/COMP/D64_EXITDOOR_1", 128.f, 72.f, 48.87f, 64.66f, 19, 0x1eff62u, 0.655f, false, 40, 60, 63, 66 },
    { "D64_EXITDOOR_1", 128.f, 72.f, 15.50f, 64.85f, 17, 0x13ff71u, 0.655f, false, 3, 23, 62, 66 },
    { "TEXTURES/COMP/D64_EXITDOOR_1", 128.f, 72.f, 15.50f, 64.85f, 17, 0x13ff71u, 0.655f, false, 3, 23, 62, 66 },
    { "D64_EXITDOOR_2", 128.f, 72.f, 31.57f, 36.47f, 95, 0x1cff1fu, 1.000f, false, 26, 36, 31, 41 },
    { "TEXTURES/COMP/D64_EXITDOOR_2", 128.f, 72.f, 31.57f, 36.47f, 95, 0x1cff1fu, 1.000f, false, 26, 36, 31, 41 },
    { "D64_EXITDOOR_2", 128.f, 72.f, 52.50f, 64.50f, 16, 0x10ff1eu, 1.000f, false, 48, 60, 63, 66 },
    { "TEXTURES/COMP/D64_EXITDOOR_2", 128.f, 72.f, 52.50f, 64.50f, 16, 0x10ff1eu, 1.000f, false, 48, 60, 63, 66 },
    { "D64_EXITDOOR_2", 128.f, 72.f, 42.61f, 64.83f, 9, 0x18ff1cu, 1.000f, false, 40, 44, 63, 66 },
    { "TEXTURES/COMP/D64_EXITDOOR_2", 128.f, 72.f, 42.61f, 64.83f, 9, 0x18ff1cu, 1.000f, false, 40, 44, 63, 66 },
    { "D64_EXITDOOR_2", 128.f, 72.f, 14.31f, 64.96f, 26, 0x16ff1fu, 1.000f, false, 3, 24, 62, 66 },
    { "TEXTURES/COMP/D64_EXITDOOR_2", 128.f, 72.f, 14.31f, 64.96f, 26, 0x16ff1fu, 1.000f, false, 3, 24, 62, 66 },
    { "D64_GREYDOOR_1", 64.f, 72.f, 32.16f, 37.07f, 68, 0x3aff39u, 0.672f, false, 22, 41, 35, 38 },
    { "TEXTURES/PEPY/DOORS/D64_GREYDOOR_1.PNG", 64.f, 72.f, 32.16f, 37.07f, 68, 0x3aff39u, 0.672f, false, 22, 41, 35, 38 },
    { "D64_GREYDOOR_2", 64.f, 72.f, 32.00f, 37.09f, 74, 0x32ff32u, 1.000f, false, 22, 41, 35, 38 },
    { "TEXTURES/PEPY/DOORS/D64_GREYDOOR_2.PNG", 64.f, 72.f, 32.00f, 37.09f, 74, 0x32ff32u, 1.000f, false, 22, 41, 35, 38 },
    { "D64_TALLDOOR_1", 64.f, 128.f, 19.00f, 122.09f, 74, 0x43ff30u, 0.654f, false, 9, 28, 120, 123 },
    { "TEXTURES/CAGE/EDITS/D64_TALLDOOR_1.PNG", 64.f, 128.f, 19.00f, 122.09f, 74, 0x43ff30u, 0.654f, false, 9, 28, 120, 123 },
    { "D64_TALLDOOR_1", 64.f, 128.f, 45.00f, 122.09f, 74, 0x43ff30u, 0.654f, false, 35, 54, 120, 123 },
    { "TEXTURES/CAGE/EDITS/D64_TALLDOOR_1.PNG", 64.f, 128.f, 45.00f, 122.09f, 74, 0x43ff30u, 0.654f, false, 35, 54, 120, 123 },
    { "D64_TALLDOOR_2", 64.f, 128.f, 19.00f, 122.03f, 76, 0x33ff32u, 1.000f, false, 8, 29, 119, 123 },
    { "TEXTURES/CAGE/EDITS/D64_TALLDOOR_2.PNG", 64.f, 128.f, 19.00f, 122.03f, 76, 0x33ff32u, 1.000f, false, 8, 29, 119, 123 },
    { "D64_TALLDOOR_2", 64.f, 128.f, 45.00f, 122.09f, 74, 0x32ff32u, 1.000f, false, 35, 54, 120, 123 },
    { "TEXTURES/CAGE/EDITS/D64_TALLDOOR_2.PNG", 64.f, 128.f, 45.00f, 122.09f, 74, 0x32ff32u, 1.000f, false, 35, 54, 120, 123 },
    { "D64_TALLDOORALPHA_1", 64.f, 128.f, 17.68f, 83.97f, 17, 0x5bff5bu, 0.493f, false, 10, 24, 83, 84 },
    { "TEXTURES/CAGE/EDITS/D64_TALLDOORALPHA_1.PNG", 64.f, 128.f, 17.68f, 83.97f, 17, 0x5bff5bu, 0.493f, false, 10, 24, 83, 84 },
    { "D64_TALLDOORALPHA_2", 64.f, 128.f, 17.68f, 84.00f, 22, 0x00ff00u, 1.000f, false, 10, 24, 83, 84 },
    { "TEXTURES/CAGE/EDITS/D64_TALLDOORALPHA_2.PNG", 64.f, 128.f, 17.68f, 84.00f, 22, 0x00ff00u, 1.000f, false, 10, 24, 83, 84 },
    { "D64_WIDEDOOR_1", 128.f, 96.f, 63.80f, 47.83f, 90, 0x3aff31u, 0.601f, false, 58, 69, 41, 53 },
    { "TEXTURES/PEPY/DOORS/D64_WIDEDOOR_1.PNG", 128.f, 96.f, 63.80f, 47.83f, 90, 0x3aff31u, 0.601f, false, 58, 69, 41, 53 },
    { "D64_WIDEDOOR_1", 128.f, 96.f, 46.33f, 91.48f, 66, 0x3bff38u, 0.601f, false, 35, 57, 90, 92 },
    { "TEXTURES/PEPY/DOORS/D64_WIDEDOOR_1.PNG", 128.f, 96.f, 46.33f, 91.48f, 66, 0x3bff38u, 0.601f, false, 35, 57, 90, 92 },
    { "D64_WIDEDOOR_1", 128.f, 96.f, 81.67f, 91.52f, 64, 0x3bff36u, 0.601f, false, 70, 92, 90, 92 },
    { "TEXTURES/PEPY/DOORS/D64_WIDEDOOR_1.PNG", 128.f, 96.f, 81.67f, 91.52f, 64, 0x3bff36u, 0.601f, false, 70, 92, 90, 92 },
    { "D64_WIDEDOOR_2", 128.f, 96.f, 63.95f, 47.92f, 112, 0x28ff25u, 1.000f, false, 57, 70, 41, 54 },
    { "TEXTURES/PEPY/DOORS/D64_WIDEDOOR_2.PNG", 128.f, 96.f, 63.95f, 47.92f, 112, 0x28ff25u, 1.000f, false, 57, 70, 41, 54 },
    { "D64_WIDEDOOR_2", 128.f, 96.f, 82.17f, 91.49f, 81, 0x2cff27u, 1.000f, false, 68, 95, 90, 92 },
    { "TEXTURES/PEPY/DOORS/D64_WIDEDOOR_2.PNG", 128.f, 96.f, 82.17f, 91.49f, 81, 0x2cff27u, 1.000f, false, 68, 95, 90, 92 },
    { "D64_WIDEDOOR_2", 128.f, 96.f, 45.67f, 91.51f, 78, 0x2bff25u, 1.000f, false, 32, 58, 90, 92 },
    { "TEXTURES/PEPY/DOORS/D64_WIDEDOOR_2.PNG", 128.f, 96.f, 45.67f, 91.51f, 78, 0x2bff25u, 1.000f, false, 32, 58, 90, 92 },
    // ---- strip
    { "D64_BRONZEWALL_LIT", 64.f, 128.f, 32.00f, 122.00f, 72, 0xffffdau, 1.000f, true, 10, 53, 120, 123 },
    { "TEXTURES/PEPY/D64_BRONZEWALL_LIT", 64.f, 128.f, 32.00f, 122.00f, 72, 0xffffdau, 1.000f, true, 10, 53, 120, 123 },
    { "D64_D1_LITE2", 64.f, 128.f, 31.00f, 36.00f, 1576, 0xfff1dfu, 1.000f, true, 10, 51, 3, 68 },
    { "TEXTURES/COMP/D64_D1_LITE2", 64.f, 128.f, 31.00f, 36.00f, 1576, 0xfff1dfu, 1.000f, true, 10, 51, 3, 68 },
    { "D64_D1_LITE4", 16.f, 128.f, 8.00f, 58.45f, 1656, 0xffeedcu, 1.000f, true, 0, 15, 0, 124 },
    { "TEXTURES/COMP/D64_D1_LITE4", 16.f, 128.f, 8.00f, 58.45f, 1656, 0xffeedcu, 1.000f, true, 0, 15, 0, 124 },
    { "D64_D1_LITE96", 64.f, 128.f, 32.00f, 54.00f, 1576, 0xfff1dfu, 1.000f, true, 9, 54, 21, 86 },
    { "TEXTURES/COMP/D64_D1_LITE96", 64.f, 128.f, 32.00f, 54.00f, 1576, 0xfff1dfu, 1.000f, true, 9, 54, 21, 86 },
    { "D64_D1_LITEMET", 128.f, 128.f, 61.00f, 70.00f, 1576, 0xfff1dfu, 1.000f, true, 24, 97, 37, 102 },
    { "TEXTURES/COMP/D64_D1_LITEMET", 128.f, 128.f, 61.00f, 70.00f, 1576, 0xfff1dfu, 1.000f, true, 24, 97, 37, 102 },
    { "D64_D1_LITESTONE", 64.f, 128.f, 33.00f, 63.00f, 1576, 0xfff1dfu, 1.000f, true, 12, 53, 30, 95 },
    { "TEXTURES/COMP/D64_D1_LITESTONE", 64.f, 128.f, 33.00f, 63.00f, 1576, 0xfff1dfu, 1.000f, true, 12, 53, 30, 95 },
    { "D64_D1LITEBLU1", 8.f, 128.f, 4.00f, 27.50f, 132, 0xffe7dau, 1.000f, true, 2, 5, 11, 43 },
    { "TEXTURES/PEPY/D64_D1LITEBLU1.PNG", 8.f, 128.f, 4.00f, 27.50f, 132, 0xffe7dau, 1.000f, true, 2, 5, 11, 43 },
    { "D64_D1LITEBLU1", 8.f, 128.f, 4.00f, 102.50f, 132, 0xffe7dau, 1.000f, true, 2, 5, 86, 118 },
    { "TEXTURES/PEPY/D64_D1LITEBLU1.PNG", 8.f, 128.f, 4.00f, 102.50f, 132, 0xffe7dau, 1.000f, true, 2, 5, 86, 118 },
    { "D64_D1LITEBLU2", 16.f, 72.f, 8.00f, 20.50f, 200, 0xffefdfu, 1.000f, true, 4, 11, 8, 32 },
    { "TEXTURES/PEPY/D64_D1LITEBLU2.PNG", 16.f, 72.f, 8.00f, 20.50f, 200, 0xffefdfu, 1.000f, true, 4, 11, 8, 32 },
    { "D64_D1LITEBLU2", 16.f, 72.f, 8.00f, 52.50f, 200, 0xffefdfu, 1.000f, true, 4, 11, 40, 64 },
    { "TEXTURES/PEPY/D64_D1LITEBLU2.PNG", 16.f, 72.f, 8.00f, 52.50f, 200, 0xffefdfu, 1.000f, true, 4, 11, 40, 64 },
    { "D64_D1LITESUPERTHIN", 16.f, 128.f, 8.00f, 64.00f, 512, 0xffe9d9u, 1.000f, true, 6, 9, 0, 127 },
    { "TEXTURES/PEPY/D64_D1LITESUPERTHIN.PNG", 16.f, 128.f, 8.00f, 64.00f, 512, 0xffe9d9u, 1.000f, true, 6, 9, 0, 127 },
    { "D64_EXITDOOR_0", 128.f, 72.f, 120.00f, 36.51f, 672, 0xfff1ddu, 1.000f, true, 113, 126, 2, 70 },
    { "TEXTURES/COMP/D64_EXITDOOR_0", 128.f, 72.f, 120.00f, 36.51f, 672, 0xfff1ddu, 1.000f, true, 113, 126, 2, 70 },
    { "D64_LITE_BLUE", 16.f, 128.f, 8.00f, 64.00f, 1984, 0x1b6cffu, 1.000f, true, 0, 15, 0, 127 },
    { "TEXTURES/PEPY/D64_LITE_BLUE.PNG", 16.f, 128.f, 8.00f, 64.00f, 1984, 0x1b6cffu, 1.000f, true, 0, 15, 0, 127 },
    { "D64_LITE_THIN", 16.f, 128.f, 8.00f, 64.00f, 1984, 0xffecd9u, 1.000f, true, 0, 15, 0, 127 },
    { "TEXTURES/PEPY/D64_LITE_THIN.PNG", 16.f, 128.f, 8.00f, 64.00f, 1984, 0xffecd9u, 1.000f, true, 0, 15, 0, 127 },
    { "D64_LITE_WIDE", 32.f, 128.f, 16.00f, 64.47f, 3328, 0xffeddbu, 1.000f, true, 1, 30, 1, 127 },
    { "TEXTURES/PEPY/D64_LITE_WIDE.PNG", 32.f, 128.f, 16.00f, 64.47f, 3328, 0xffeddbu, 1.000f, true, 1, 30, 1, 127 },
    { "D64_METAL7", 64.f, 128.f, 32.83f, 121.50f, 275, 0xfffaebu, 1.000f, true, 8, 57, 118, 124 },
    { "TEXTURES/PEPY/D64_METAL7.PNG", 64.f, 128.f, 32.83f, 121.50f, 275, 0xfffaebu, 1.000f, true, 8, 57, 118, 124 },
    { "D64_SILVER2", 64.f, 128.f, 32.24f, 33.50f, 417, 0xfff2e2u, 1.000f, true, 10, 53, 19, 47 },
    { "TEXTURES/PEPY/D64_SILVER2.PNG", 64.f, 128.f, 32.24f, 33.50f, 417, 0xfff2e2u, 1.000f, true, 10, 53, 19, 47 },
    { "D64_SILVER2", 64.f, 128.f, 32.24f, 94.50f, 417, 0xfff2e2u, 1.000f, true, 10, 53, 80, 108 },
    { "TEXTURES/PEPY/D64_SILVER2.PNG", 64.f, 128.f, 32.24f, 94.50f, 417, 0xfff2e2u, 1.000f, true, 10, 53, 80, 108 },
    // ---- switch
    { "D64_BLUESKULLSWITCH_ON", 64.f, 128.f, 32.00f, 83.54f, 106, 0x1bff21u, 1.000f, false, 26, 37, 78, 88 },
    { "TEXTURES/COMP/D64_BLUESKULLSWITCH_ON", 64.f, 128.f, 32.00f, 83.54f, 106, 0x1bff21u, 1.000f, false, 26, 37, 78, 88 },
    { "D64_BRICKWARN_ON", 64.f, 128.f, 32.00f, 79.10f, 70, 0x32ff32u, 1.000f, false, 22, 41, 77, 80 },
    { "TEXTURES/COMP/D64_BRICKWARN_ON", 64.f, 128.f, 32.00f, 79.10f, 70, 0x32ff32u, 1.000f, false, 22, 41, 77, 80 },
    { "D64_BRICKWARN_ON", 64.f, 128.f, 38.53f, 94.73f, 31, 0x33ff33u, 1.000f, false, 30, 42, 89, 97 },
    { "TEXTURES/COMP/D64_BRICKWARN_ON", 64.f, 128.f, 38.53f, 94.73f, 31, 0x33ff33u, 1.000f, false, 30, 42, 89, 97 },
    { "D64_BRICKWARN_ON", 64.f, 128.f, 23.71f, 95.88f, 24, 0x33ff33u, 1.000f, false, 21, 27, 93, 97 },
    { "TEXTURES/COMP/D64_BRICKWARN_ON", 64.f, 128.f, 23.71f, 95.88f, 24, 0x33ff33u, 1.000f, false, 21, 27, 93, 97 },
    { "D64_BRONZESWITCH_ON", 128.f, 128.f, 64.00f, 79.54f, 52, 0x29ff58u, 1.000f, false, 55, 72, 77, 82 },
    { "TEXTURES/COMP/D64_BRONZESWITCH_ON", 128.f, 128.f, 64.00f, 79.54f, 52, 0x29ff58u, 1.000f, false, 55, 72, 77, 82 },
    { "D64_BROWN1LEVER_ON", 64.f, 128.f, 32.00f, 79.09f, 74, 0x32ff32u, 1.000f, false, 22, 41, 77, 80 },
    { "TEXTURES/COMP/D64_BROWN1LEVER_ON", 64.f, 128.f, 32.00f, 79.09f, 74, 0x32ff32u, 1.000f, false, 22, 41, 77, 80 },
    { "D64_BROWN1LEVER_ON", 64.f, 128.f, 24.02f, 95.78f, 29, 0x33ff33u, 1.000f, false, 21, 27, 93, 97 },
    { "TEXTURES/COMP/D64_BROWN1LEVER_ON", 64.f, 128.f, 24.02f, 95.78f, 29, 0x33ff33u, 1.000f, false, 21, 27, 93, 97 },
    { "D64_BROWN1LEVER_ON", 64.f, 128.f, 39.98f, 95.78f, 29, 0x33ff33u, 1.000f, false, 36, 42, 93, 97 },
    { "TEXTURES/COMP/D64_BROWN1LEVER_ON", 64.f, 128.f, 39.98f, 95.78f, 29, 0x33ff33u, 1.000f, false, 36, 42, 93, 97 },
    { "D64_BROWN1SWITCH_ON", 64.f, 128.f, 32.00f, 83.54f, 106, 0x1bff21u, 1.000f, false, 26, 37, 78, 88 },
    { "TEXTURES/COMP/D64_BROWN1SWITCH_ON", 64.f, 128.f, 32.00f, 83.54f, 106, 0x1bff21u, 1.000f, false, 26, 37, 78, 88 },
    { "D64_BROWNGREENSWITCH_ON", 64.f, 128.f, 32.00f, 83.54f, 106, 0x1bff21u, 1.000f, false, 26, 37, 78, 88 },
    { "TEXTURES/COMP/D64_BROWNGREENSWITCH_ON", 64.f, 128.f, 32.00f, 83.54f, 106, 0x1bff21u, 1.000f, false, 26, 37, 78, 88 },
    { "D64_BROWNLEVER_ON", 128.f, 128.f, 64.00f, 79.10f, 70, 0x32ff32u, 1.000f, false, 54, 73, 77, 80 },
    { "TEXTURES/COMP/D64_BROWNLEVER_ON", 128.f, 128.f, 64.00f, 79.10f, 70, 0x32ff32u, 1.000f, false, 54, 73, 77, 80 },
    { "D64_BROWNLEVER_ON", 128.f, 128.f, 55.71f, 95.88f, 24, 0x33ff33u, 1.000f, false, 53, 59, 93, 97 },
    { "TEXTURES/COMP/D64_BROWNLEVER_ON", 128.f, 128.f, 55.71f, 95.88f, 24, 0x33ff33u, 1.000f, false, 53, 59, 93, 97 },
    { "D64_BROWNLEVER_ON", 128.f, 128.f, 72.10f, 95.90f, 25, 0x33ff33u, 1.000f, false, 68, 74, 93, 97 },
    { "TEXTURES/COMP/D64_BROWNLEVER_ON", 128.f, 128.f, 72.10f, 95.90f, 25, 0x33ff33u, 1.000f, false, 68, 74, 93, 97 },
    { "D64_COMPSWITCH_ON", 64.f, 128.f, 32.00f, 79.54f, 52, 0x29ff58u, 1.000f, false, 23, 40, 77, 82 },
    { "TEXTURES/COMP/D64_COMPSWITCH_ON", 64.f, 128.f, 32.00f, 79.54f, 52, 0x29ff58u, 1.000f, false, 23, 40, 77, 82 },
    { "D64_DIRTSWITCH_ON", 64.f, 128.f, 32.00f, 25.54f, 52, 0x29ff58u, 1.000f, false, 23, 40, 23, 28 },
    { "TEXTURES/COMP/D64_DIRTSWITCH_ON", 64.f, 128.f, 32.00f, 25.54f, 52, 0x29ff58u, 1.000f, false, 23, 40, 23, 28 },
    { "D64_GLARTANLEVER_ON", 128.f, 128.f, 64.00f, 79.10f, 70, 0x32ff32u, 1.000f, false, 54, 73, 77, 80 },
    { "TEXTURES/COMP/D64_GLARTANLEVER_ON", 128.f, 128.f, 64.00f, 79.10f, 70, 0x32ff32u, 1.000f, false, 54, 73, 77, 80 },
    { "D64_GLARTANLEVER_ON", 128.f, 128.f, 55.71f, 95.88f, 24, 0x33ff33u, 1.000f, false, 53, 59, 93, 97 },
    { "TEXTURES/COMP/D64_GLARTANLEVER_ON", 128.f, 128.f, 55.71f, 95.88f, 24, 0x33ff33u, 1.000f, false, 53, 59, 93, 97 },
    { "D64_GLARTANLEVER_ON", 128.f, 128.f, 72.10f, 95.90f, 25, 0x33ff33u, 1.000f, false, 68, 74, 93, 97 },
    { "TEXTURES/COMP/D64_GLARTANLEVER_ON", 128.f, 128.f, 72.10f, 95.90f, 25, 0x33ff33u, 1.000f, false, 68, 74, 93, 97 },
    { "D64_GRAY1SWITCH_ON", 64.f, 128.f, 31.48f, 87.83f, 84, 0x19ff19u, 1.000f, false, 26, 36, 83, 92 },
    { "TEXTURES/COMP/D64_GRAY1SWITCH_ON", 64.f, 128.f, 31.48f, 87.83f, 84, 0x19ff19u, 1.000f, false, 26, 36, 83, 92 },
    { "D64_GRAYSWITCH_ON", 64.f, 128.f, 32.00f, 79.54f, 52, 0x29ff58u, 1.000f, false, 23, 40, 77, 82 },
    { "TEXTURES/COMP/D64_GRAYSWITCH_ON", 64.f, 128.f, 32.00f, 79.54f, 52, 0x29ff58u, 1.000f, false, 23, 40, 77, 82 },
    { "D64_GRAYVINESWITCH_ON", 64.f, 128.f, 32.00f, 83.54f, 106, 0x1bff21u, 1.000f, false, 26, 37, 78, 88 },
    { "TEXTURES/COMP/D64_GRAYVINESWITCH_ON", 64.f, 128.f, 32.00f, 83.54f, 106, 0x1bff21u, 1.000f, false, 26, 37, 78, 88 },
    { "D64_GREYBRICKSWITCH_ON", 64.f, 128.f, 32.00f, 79.54f, 52, 0x29ff58u, 1.000f, false, 23, 40, 77, 82 },
    { "TEXTURES/COMP/D64_GREYBRICKSWITCH_ON", 64.f, 128.f, 32.00f, 79.54f, 52, 0x29ff58u, 1.000f, false, 23, 40, 77, 82 },
    { "D64_HEXSWITCH_ON", 64.f, 128.f, 31.48f, 75.83f, 84, 0x19ff19u, 1.000f, false, 26, 36, 71, 80 },
    { "TEXTURES/COMP/D64_HEXSWITCH_ON", 64.f, 128.f, 31.48f, 75.83f, 84, 0x19ff19u, 1.000f, false, 26, 36, 71, 80 },
    { "D64_HOTBRICKSWITCHDOWN_ON", 64.f, 128.f, 32.03f, 86.59f, 47, 0x2dff25u, 1.000f, false, 27, 36, 83, 92 },
    { "TEXTURES/COMP/D64_HOTBRICKSWITCHDOWN_ON", 64.f, 128.f, 32.03f, 86.59f, 47, 0x2dff25u, 1.000f, false, 27, 36, 83, 92 },
    { "D64_HOTBRICKSWITCHUP_ON", 64.f, 128.f, 32.07f, 89.50f, 46, 0x2dff25u, 1.000f, false, 27, 36, 83, 92 },
    { "TEXTURES/COMP/D64_HOTBRICKSWITCHUP_ON", 64.f, 128.f, 32.07f, 89.50f, 46, 0x2dff25u, 1.000f, false, 27, 36, 83, 92 },
    { "D64_MODSWITCH_ON", 64.f, 128.f, 31.48f, 83.83f, 84, 0x19ff19u, 1.000f, false, 26, 36, 79, 88 },
    { "TEXTURES/COMP/D64_MODSWITCH_ON", 64.f, 128.f, 31.48f, 83.83f, 84, 0x19ff19u, 1.000f, false, 26, 36, 79, 88 },
    { "D64_SILVER72SWITCH_ON", 64.f, 72.f, 32.00f, 25.54f, 52, 0x29ff58u, 1.000f, false, 23, 40, 23, 28 },
    { "TEXTURES/COMP/D64_SILVER72SWITCH_ON", 64.f, 72.f, 32.00f, 25.54f, 52, 0x29ff58u, 1.000f, false, 23, 40, 23, 28 },
    { "D64_SKULLSWITCH_ON", 64.f, 128.f, 22.50f, 86.50f, 19, 0xff001eu, 1.000f, false, 18, 26, 85, 87 },
    { "TEXTURES/COMP/D64_SKULLSWITCH_ON", 64.f, 128.f, 22.50f, 86.50f, 19, 0xff001eu, 1.000f, false, 18, 26, 85, 87 },
    { "D64_SKULLSWITCH_ON", 64.f, 128.f, 40.50f, 86.50f, 19, 0xff001eu, 1.000f, false, 36, 44, 85, 87 },
    { "TEXTURES/COMP/D64_SKULLSWITCH_ON", 64.f, 128.f, 40.50f, 86.50f, 19, 0xff001eu, 1.000f, false, 36, 44, 85, 87 },
    { "D64_SLADWARN_ON", 64.f, 128.f, 32.00f, 79.10f, 70, 0x32ff32u, 1.000f, false, 22, 41, 77, 80 },
    { "TEXTURES/COMP/D64_SLADWARN_ON", 64.f, 128.f, 32.00f, 79.10f, 70, 0x32ff32u, 1.000f, false, 22, 41, 77, 80 },
    { "D64_SLADWARN_ON", 64.f, 128.f, 38.53f, 94.73f, 31, 0x33ff33u, 1.000f, false, 30, 42, 89, 97 },
    { "TEXTURES/COMP/D64_SLADWARN_ON", 64.f, 128.f, 38.53f, 94.73f, 31, 0x33ff33u, 1.000f, false, 30, 42, 89, 97 },
    { "D64_SLADWARN_ON", 64.f, 128.f, 23.71f, 95.88f, 24, 0x33ff33u, 1.000f, false, 21, 27, 93, 97 },
    { "TEXTURES/COMP/D64_SLADWARN_ON", 64.f, 128.f, 23.71f, 95.88f, 24, 0x33ff33u, 1.000f, false, 21, 27, 93, 97 },
    { "D64_STARTANSWITCH_ON", 64.f, 128.f, 32.00f, 79.54f, 52, 0x29ff58u, 1.000f, false, 23, 40, 77, 82 },
    { "TEXTURES/COMP/D64_STARTANSWITCH_ON", 64.f, 128.f, 32.00f, 79.54f, 52, 0x29ff58u, 1.000f, false, 23, 40, 77, 82 },
    { "D64_STONESTRIPSWITCH_ON", 64.f, 128.f, 32.00f, 79.54f, 52, 0x29ff58u, 1.000f, false, 23, 40, 77, 82 },
    { "TEXTURES/COMP/D64_STONESTRIPSWITCH_ON", 64.f, 128.f, 32.00f, 79.54f, 52, 0x29ff58u, 1.000f, false, 23, 40, 77, 82 },
    { "D64_STONESWITCH_ON", 64.f, 128.f, 32.00f, 79.54f, 52, 0x29ff58u, 1.000f, false, 23, 40, 77, 82 },
    { "TEXTURES/COMP/D64_STONESWITCH_ON", 64.f, 128.f, 32.00f, 79.54f, 52, 0x29ff58u, 1.000f, false, 23, 40, 77, 82 },
    { "D64_TEKSWITCH_ON", 64.f, 128.f, 31.48f, 83.83f, 84, 0x19ff19u, 1.000f, false, 26, 36, 79, 88 },
    { "TEXTURES/COMP/D64_TEKSWITCH_ON", 64.f, 128.f, 31.48f, 83.83f, 84, 0x19ff19u, 1.000f, false, 26, 36, 79, 88 },
};
